version: '3.3'

networks:
  dockerappnt:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: ngix
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - dockerappnt

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravelapp
      - DB_USERNAME=root
      - DB_PASSWORD=
    networks:
      - dockerappnt

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    # volumes:
      # - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - dockerappnt